[build]
dir_path = "asphalt/ReplicatedStorage"
module_path = "out/Shared/Asphalt.luau"
efficient_build_includes_all_local_files = true
asset_usage_audit_script_directories = ["src"]

[build.libraries]
media = "nightcycle/media@1.0.0"

[build.publish]
publish_to_group = true
entity_id = 4181328

[media.audio]
dir_path = "asphalt/SoundService"
compression_directory_instance = "SoundGroup"
sources = [
	"asset/audio",
	"media/audio"
]

[media.image]
sources = [
	"asset/image",
	"media/image"
]

[media.material]
dir_path = "asphalt/MaterialService"
sources = [
	"asset/material",
	"media/material"
]

[media.mesh]
sources = [
	"asset/mesh",
	"media/mesh"
]

[media.model]
sources = [
	"asset/model",
	"media/model"
]

[media.particle]
sources = [
	"asset/particle",
	"media/particle"
]

[media.animation]
sources = [
	"asset/animation",
	"media/animation"
]
