[[boot_order]]
modules = [
	"Analytics",
	"DataTreeService",
	"CollisionGroup",
	"Barrier",
	"DestructibleService",
	"Environment",
	"ProjectileService",
	"Lobby",
	"Player",
	"Leviathan",
	"Vehicle",
	"BuildService",
	"Announcement",
	"RoundService",
]
is_shared = false
domain_path = "game/ServerScriptService/Server"
build_path = "out/Server/Boot.server.luau"

[[boot_order]]
modules = [
	"Analytics",
	"DataTree",
	"HideServerPart",
	"UI",
	"ActionService",
	"Projectile",
	"Lobby",
	"HUD",
	"Map",
	"Weapons",
	"Leviathan",
]
is_shared = false
domain_path = "game/ReplicatedStorage/Client"
build_path = "out/Client/Boot.client.luau"


[[boot_order]]
modules = [
	"StudioSequence",
]
is_shared = false
domain_path = "game/ReplicatedStorage/Packages"
build_path = "out/First/Boot.client.luau"
