build_path = "out/Shared/PseudoEnum.luau"
use_union_types_for_tree = false
use_union_types_for_export = false
[enums]
BiomeType = [ "Ice", "Plains", "Forest", "Rainforest", "Savanna", "Grassland", "Tundra", "Snow", "Desert", "Cliff", "City",]
BuildFailType = [ "None", "IntersectionFull", "DeadNode", "SameNode", "AlreadyConnected", "BothCity", "TooClose", "Incline",]
BuildGuiCursorState = ["None", "Default", "CellHover", "CellDraw", "CellDelete", "CellElevate", "TerrainAim", "CellConnect",]
BuildMethodType = [ "None", "BranchToBranchConnect", "BranchToOriginConnect", "BranchToBranchExtend", "BranchToOriginExtend", "BranchToPointExtend", "OriginToOriginConnect", "OriginToBranchConnect", "OriginToOriginExtend", "OriginToBranchExtend", "OriginToPointExtend",]
BuildState = [ "Default", "StartDraw", "FinishDraw", "Demolish", "Configure", "StartVehicleRoute", "SelectNextCity", "SelectCityPurchase",]
ConfigurationMode = [ "Performance", "Customization",]
CurvePartType = [ "Block", "Wedge", "Tube",]
FoundationType = [ "City", "Ground", "Bridge", "LandBridge", "Tunnel", "UnderwaterTunnel",]
FuelType = [ "Coal", "Oil", "Electric",]
InfrastructureType = [ "None", "Road", "Rail", "Monorail", "HighSpeedRail", "MaglevRail", "HyperloopRail",]
LaneSegmentStageId = [ "Entrance", "Center", "Exit",]
MapStage = [ "Unloaded", "Solving", "Terrain", "Decorating", "Cities", "Loaded",]
MerchStatType = [ "Price", "Quantity", "Mass",]
RouteEditorState = [ "Default", "SelectDestination", "SelectOrigin", "BuyItems", "SellItems",]
RouteLayerId = [ "Intersection", "Lane", "LaneSegment",]
VehiclePurpose = [ "Freight", "Passenger",]
ContrastStandardType = [ "Default", "LargeText", "Incidental", "Logotype",]
GuiAlignmentType = [ "Center", "Left", "Right", "Top", "Bottom", "TopLeft", "TopRight", "BottomLeft", "BottomRight",]
GuiColorPalette = [ "Primary1", "Primary2", "Primary3", "Primary4", "Primary5", "Primary6", "Secondary1", "Secondary2", "Secondary3", "Secondary4", "Secondary5", "Secondary6", "Tertiary1", "Tertiary2", "Tertiary3", "Tertiary4", "Tertiary5", "Tertiary6", "Surface1", "Surface2", "Surface3", "Surface4", "Surface5", "Surface6", "Warning", "Error", "Loss1", "Loss2", "Loss3", "Loss4", "Loss5", "Loss6", "Gain1", "Gain2", "Gain3", "Gain4", "Gain5", "Gain6", "Dark1", "Dark2", "Dark3", "Dark4", "Dark5", "Dark6", "Light1", "Light2", "Light3", "Light4", "Light5", "Light6",]
GuiDensityModifier = [ "Default", "High", "Low",]
GuiThemeType = [ "Dark", "Light",]
GuiTypography = [ "Overline", "Caption", "Body2", "Body1", "Subtitle2", "Subtitle1", "Button", "Headline6", "Headline5", "Headline4", "Headline3", "Headline2", "Headline1",]
GuiCategoryType = [ "Background", "Panel", "Card", "Frame", "Item", "Button", "Label", "Bar", "Toggle",]
